### ISSUE TITLE
Release 2.2.0 breaks newline expansion in parameters (e.g. "notes")

### ISSUE THREAD

**Issue by crrobinson14** [bitrise-io/steps-hockeyapp-deploy#11]
The latest version changes how parameters are passed through the step and out to cURL. Previously, it was possible to include newlines in the "notes" field. This was useful for building things like changelogs using the "Markdown" Notes Type. In 2.2.0 these are no longer preserved and multi-line values are now passed through as a single-line string.

**Comment by godrei** [comment]
Hi, we released a new version of step (https://github.com/bitrise-io/steps-hockeyapp-deploy/releases/tag/2.2.1), which includes the fix for multiline notes.
Thanks for your contribution @crrobinson14 ! :)
