### ISSUE TITLE
Enable IPA and dSYM to be uploaded to different apps

### ISSUE THREAD

**Issue by fjcaetano** [bitrise-io/steps-hockeyapp-deploy#19]
HockeyApp docs states that apps that are already in production and have pre-release options must be configured twice. One as **Store** and one as **Beta**.

Therefore, there should be an option to deploy the IPA to one config (using one App ID) and the dSYM to another (using a different App ID), where the IPA should go to the **Beta** config and the dSYM to the **Store** config.

Perhaps it would be interesting to have a new step to upload only the dSYM, considering that releases that are submitted to the AppStore don't need to be deployed to HockeyApp, only their dSYMs must be submitted in order for HockeyApp to be able to symbolicate their crashes and exceptions.

**Comment by viktorbenei** [comment]
Sorry, we didn't have the time today to work on this, but we will try to get back to you ASAP!

**Comment by viktorbenei** [comment]
Scheduled for next Monday.

**Comment by godrei** [comment]
@fjcaetano Just a heads up, we'll come back to this task a bit later, we just have a couple of other tasks we have to deal with first 😊

**Comment by godrei** [comment]
Hi @fjcaetano ,
i checked out the articles you sent:
[organize-development-and-production-apps](https://support.hockeyapp.net/kb/app-management-2/how-to-organize-development-and-production-apps-for-distribution)  
[Beta version then Store version with the same bundle ID](https://support.hockeyapp.net/discussions/problems/40578-beta-version-then-store-version-with-the-same-bundle-id)  

But i can not found why *should be an option to deploy the IPA to one config (using one App ID) and the dSYM to another (using a different App ID), where the IPA should go to the Beta config and the dSYM to the Store config.*
I think if you separate `store` and `beta` builds, then `store` *ipa* and *dsym* should be uploaded to `store` app, and `beta` artifacts to `beta` app.

Am i missing something?

**Comment by fjcaetano** [comment]
Hi @godrei, the HockeySDK in my app is configured to point to the `store` build. This means that it is the `store` build that receives the crash reports. However, in order to be able to deliver AdHoc builds, I must upload them to a `beta` build in HockeyApp, otherwise my team won't be able to download the AdHoc.

This means that the `IPA` and `dSYM` are being uploaded to the `beta` build, but the crashes and feedbacks (everything related to the HockeySDK) are being logged in the `store` build, which makes the crashes unreadable since they're not symbolicated. That's why there should be an option to upload the `IPA` and `dSYM` to different apps.

I've worked around this by manually uploading the dSYM zip to the `store` app.

**Comment by godrei** [comment]
Hi @fjcaetano ,
why you just do not upload the `store` build's dsym?

**Comment by fjcaetano** [comment]
@godrei, that's what I'm doing, but manually. I opened this issue because I think there should be an automated way to do this.

**Comment by godrei** [comment]
@fjcaetano do you release your `store` build with bitrise too?

**Comment by fjcaetano** [comment]
Not to HockeyApp. I have another workflow that runs on the `master` branch that releases a build directly to the AppStore and deploys the dSYM to Bitrise files. Then I manually download this dSYM and upload it to the HockeyApp `store` build.

**Comment by godrei** [comment]
I think the prefered way would be to create two workflows, one for `ad hoc` deploy and the other one for `app store` deploy, both workflow with archive -> deploy -> hockey-app deploy. `ad hoc` artifacts to `beta` app on hockey, `app store` artifacts to `store` app.

**Comment by fjcaetano** [comment]
That is exactly what I'm doing.

**Comment by fjcaetano** [comment]
That is exactly what I'm doing, but the `app store` artifact only uploads to the AppStore, not to HockeyApp

**Comment by godrei** [comment]
Why do you not upload to the HockeyApp too?

**Comment by fjcaetano** [comment]
Because it doesn't make very much sense. As I understand, I can't release the `store` configs in HockeyApp to my team, so it would only make sense to upload the dSYM. Though, I honestly don't know if that is an alternative.

**Comment by godrei** [comment]
If you use hockey-app deploy step for `store` config then you do not need to upload dsym manually from ad-hoc build. you can not download or use the `store` ipa that is rigth, but upload does not case any issue.

**Comment by fjcaetano** [comment]
@godrei I'll submit a new release to the AppStore later this week and I'll try this. I'll came back to you with the results then, ok?

**Comment by godrei** [comment]
@fjcaetano nice, thanks!

**Comment by godrei** [comment]
Hi @fjcaetano, any news on this question?

**Comment by godrei** [comment]
Closing as we did not receive a reply - @fjcaetano  please let us know if we can help with anything and we'll reopen this issue!

**Comment by fjcaetano** [comment]
I completely forgot to come back to you, and I apologise.

I am being able to make it work by adding two consecutive "Deploy to HockeyApp" steps, one pointing to the *beta* app and another to the *store* app.

**Comment by viktorbenei** [comment]
Thanks for the response & sharing your solution @fjcaetano !
