### ISSUE TITLE
Markdown support for the attachment `formatting_mode`

### ISSUE THREAD

**Issue by Bunk** [bitrise-io/steps-hockeyapp-deploy#20]
There's a way to support Markdown formatting in attachments, although it's buried in their documentation a bit.  

See the "Message Formatting" section on [the Slack API docs page](https://api.slack.com/docs/message-formatting).

```json
{
    "attachments": [
        {
            "title": "Title",
            "pretext": "Pretext _supports_ mrkdwn",
            "text": "Testing *right now!*",
            "mrkdwn_in": ["text", "pretext"]
        }
    ]
}
```

**Comment by viktorbenei** [comment]
wrong repo, the right one is https://github.com/bitrise-io/steps-slack-message - related PR: https://github.com/bitrise-io/steps-slack-message/pull/10 ;)
