### ISSUE TITLE
Inject CHANGELOG in the note

### ISSUE THREAD

**Issue by juliengdt** [bitrise-io/steps-hockeyapp-deploy#23]
Hello,

It could be great if , for the upload, the attached note on hockeyApp can be the content of the changelog.md/txt file of the current repo

Cheers from France

TAG: enhancement

**Comment by godrei** [comment]
Hi @juliengdt ,

thanks for the issue!

Could you please create a feature request on our discuss page: https://discuss.bitrise.io/c/feature-request

**Comment by viktorbenei** [comment]
Hi @juliengdt ,

Please see: https://devcenter.bitrise.io/tips-and-tricks/expose-environment-variable/

It's as simple as adding a Script step before the Hockey App step with:

```
envman add --key MY_RELEASE_NOTE --valuefile ./path/to/changelog.txt
```

then you can use the `$MY_RELEASE_NOTE` env var in subsequent steps.

If you'd have any questions just let us know! :)

**Comment by viktorbenei** [comment]
We can of course keep this issue open to have a built in solution, right in this step, but the solution above is generic and can be used with any step which has a "notes" type input.

**Comment by viktorbenei** [comment]
Ahh, checking the times in this thread this issue might have been created before we added the notes input in this step? 🤔

**Comment by viktorbenei** [comment]
Thread was linked from: https://discuss.bitrise.io/t/possible-to-get-release-notes-into-the-hockey-app-step/4668

**Comment by viktorbenei** [comment]
Anyway, I'll close this here for now, if there's something missing feel free to create a new one!
