### ISSUE TITLE
Generated Output Variable Names

### ISSUE THREAD

**Issue by lengk** [bitrise-io/steps-hockeyapp-deploy#27]
Is there a way to change the outputed Enviroment Variables from 

`$HOCKEYAPP_DEPLOY_PUBLIC_URL`

to 

`$HOCKEYAPP_IOS_DEPLOY_PUBLIC_URL` 

Also a similar change to the for the Android App? Otherwise you can't get both the link for the Android app and the iOS app in the build process.

**Comment by godrei** [comment]
Hi, you can alias any output env: https://discuss.bitrise.io/t/monthly-release-of-bitrise-cli-tools-and-summary-of-updates-may-2017-cli-v1-6-1/1690 [2. Step Output Aliases] section.
