### ISSUE TITLE
Deploy fails with 404, "app not found"

### ISSUE THREAD

**Issue by konstantinbe** [bitrise-io/steps-hockeyapp-deploy#29]
Hello everyone,

I'm getting the following error when deploying to HockeyApp:

![bildschirmfoto 2018-07-05 um 10 42 11](https://user-images.githubusercontent.com/331694/42312702-4f6ba40e-8041-11e8-9071-59b5f5b86346.png)

If I take the artifacts (`.ipa` & `.dSYM.zip`) and upload it to HockeyApp manually via the website, it works. Can't find a way to log the full request.

Any advice and suggestions will be greatly appreciated. ❤️

**Comment by koral--** [comment]
Most possible reasons:
* app id is invalid 
* API token does not have access to that app

**Comment by trapacska** [comment]
Hey @konstantinbe !

Exactly what @koral-- mentioned above! Could you please double check those, and let us know if that was the issue? 🚀

**Comment by konstantinbe** [comment]
Thanks @koral-- & @trapacska, that was exactly it, I should've checked in the first place. 🤦‍♂️
